USE TeodoroCalleLara_Banco_10092021;

/*MOSTRAR*/
CREATE PROCEDURE CLIENTES_MEDELLIN()
SELECT * FROM CLIENTE WHERE CIUDAD = 'MEDELLIN';

/*-------------------ACTUALIZAR DIRECCION DE UN USUARIO-------------------------*/
DELIMITER $$
CREATE PROCEDURE ACTUALIZA_CLIENTE_DIRECCION(CALLE VARCHAR(255), NUMERO INT, IDCLIENTE INT)
	BEGIN
		UPDATE CLIENTE C SET C.calle = CALLE, C.numero = NUMERO WHERE C.idCliente = IDCLIENTE; 
        SELECT * FROM CLIENTE C WHERE C.idCliente = IDCLIENTE;
	END
$$
DELIMITER ;



/*-------------------CREAR UN NUEVO EMPLEADO-----------------------*/
DELIMITER $$
CREATE PROCEDURE CREAR_CLIENTE(ID_EMPLEADO INT,
NOMBRE VARCHAR(255),
PRIMER_APELLIDO VARCHAR(255),
SEGUNDO_APELLIDO VARCHAR(255),
CALLE VARCHAR(255),
NUMERO INT,
CIUDAD VARCHAR(255),
FECHA_DE_INGRESO DATE,
NUMERO_DE_TELEFONO INT)
	BEGIN 
		INSERT INTO CLIENTE 
        VALUES (NULL,ID_EMPLEADO,
        NOMBRE,
        PRIMER_APELLIDO,
        SEGUNDO_APELLIDO,
		CALLE,
        NUMERO,
        CIUDAD,
        FECHA_DE_INGRESO, 
        NUMERO_DE_TELEFONO);
        SELECT * FROM CLIENTE C WHERE C.idCliente = last_insert_id();
    END                         
$$
DELIMITER ;


             
/*-------------------ELIMINAR UN CLIENTE-------------------------*/
DELIMITER $$
CREATE PROCEDURE ELIMINAR_CLIENTE(IDCLIENTE INT)
	BEGIN
		DELETE FROM CLIENTE C WHERE C.idCliente = IDCLIENTE;
		SELECT * FROM CLIENTE;
    END
$$
DELIMITER ; 
DROP PROCEDURE ELIMINAR_CLIENTE;


/*-------------------CALCULAR LOS DIAS QUE LLEVA UN EMPLEADO LABORANDO-------------------------*/
DELIMITER $$
CREATE PROCEDURE CALCULA_DIAS_LABORADOS(FECHA_INGRESO DATE, ID_EMPLEADO INT)
	BEGIN
		DECLARE YEAR_ACTUAL DATE;
        SET YEAR_ACTUAL = NOW();
		SELECT E.nombre AS 'NOMBRE', 
        E.apellidop AS 'PRIMER APELLIDO', 
        E.apellidoM AS 'SEGUNDO APELLIDO',
        DATEDIFF(NOW(),FECHA_INGRESO) AS 'DIAS LABORADOS' FROM EMPLEADO E WHERE E.idEmpleado = ID_EMPLEADO;
    END
$$
DELIMITER ;  
 

/*RELACIONAR LAS TABLAS CLIENTE CON EMPLEADO*/
SELECT E.nombre,E.apellidoP,E.apellidoM,C.nombre,C.apellidoP,C.apellidoM,C.ciudad FROM EMPLEADOS_IJ E INNER JOIN CLIENTES_IJ C ON E.idEmpleado = C.idEmpleado WHERE C.CIUDAD = 'MEDELLIN';

/*TRIGGER*/
CREATE TRIGGER CLIENTE_AI AFTER INSERT ON CLIENTE FOR EACH ROW 
INSERT INTO REG_CLIENTES(idCliente,idEmpleado,nombre,apellidoP,apellidoM,calle,numero,ciudad,fechaIngreso,numeroTelefono,USUARIO,FECHA_REGISTRO)
VALUES (NEW.idCliente,NEW.idEmpleado,NEW.nombre,NEW.apellidoP,NEW.apellidoM,NEW.calle,NEW.numero,
		NEW.ciudad,NEW.fechaIngreso,NEW.numeroTelefono,CURRENT_USER,NOW());
        
        
CREATE TRIGGER EMPLEADO_AD AFTER DELETE ON EMPLEADO FOR EACH ROW
INSERT INTO REG_EMPLEADOS(idEmpleado,nombre,apellidoP,apellidoM,fechaIngreso,antiguedad) 
VALUES(OLD.idEmpleado,OLD.nombre,OLD.apellidoP,OLD.apellidoM,OLD.fechaIngreso,DATEDIFF(YEAR,NEW.fechaIngreso,CURDATE())); 
        


